#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

sourceIfPresent() {
	if [[ -s "$1" ]]; then
		source "$1"
	fi
}

# Source Prezto.
sourceIfPresent "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# iTerm2 integration.
sourceIfPresent "${ZDOTDIR:-$HOME}/.zprezto/iterm2.zsh"